
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract task3_2 {

    struct tasks{
        string name;
        uint32 time;
        bool done;
    }

    mapping (int8 => tasks) public newTask;
    
    int8 public index = 1;
    int8 public numberOfTasks = 0;


    //добавление задачи
    function addTask(string _name, bool done) public {
        newTask[index] = tasks(_name ,now , false); 
        numberOfTasks++;
        index++;
        tvm.accept();
    } 
    // получить задачу по ключу
    function getTask(int8 key) public returns(string name, uint32 time, bool done){  
        return (newTask[key].name, newTask[key].time, newTask[key].done); 
        tvm.accept();      
    }

    // количество открытых задач
    function numbTasks() public returns(int8){
        return numberOfTasks;
    }

    // список задач
    function getList() public returns(string){
        for( int8 i = 1; i <= index +1; i++){
            return newTask[i].name; 
        }
    } 

    // задача выполнена
    function isDone(int8 key) public{
        newTask[key].done = true;
    }

    //удаление
    function remove(int8 key) public{
        delete newTask[key];
        numberOfTasks -= 1;
    }
}
